config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books, only: ['index'] do
    collection do
      get 'with_quantity'
    end
  end
  resources :stores, only: ['index', 'show']
end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :stock

  scope :order_by_author_name, -> {
    joins(:author).order('authors.name ASC, books.id ASC')
  }

  scope :order_by_stock_quantity, -> {
    joins('LEFT OUTER JOIN stocks ON stocks.book_id = books.id')
      .group('books.id')
      .select('books.id, books.title, SUM(stocks.quantity) as sum_quantity')
      .order('sum_quantity DESC, books.id ASC')
    }
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :store
  belongs_to :book

  scope :in_store, ->(store) { where(store_id: store.id) }
end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_breadcrumb 'Home', :root_path
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order_by_author_name
  end

  def with_quantity
    @books = Book.order_by_stock_quantity
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  add_breadcrumb 'shops', :stores_path

  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
    @stocks = Stock.in_store(@store)
      .joins(:book).order('books.title ASC')
      .includes(book: :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/books/index.html.haml
- title 'Books'

%table
  %tr
    %th book id
    %th title
    %th author
    %th author_id

  - @books.each do |book|
    %tr
      %td= book.id
      %td= book.title
      %td= book.author.name
      %td= book.author.id

ordered by author name and book id.

app/views/books/with_quantity.html.haml
- title 'Books with quantity among all shops'

%table
  %tr
    %th book id
    %th title
    %th quantity

  - @books.each do |book|
    %tr
      %td= book.id
      %td= book.title
      %td= book.sum_quantity || 0

ordered by quantity and book id.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Bookstore
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %h1= yield(:title)
    = render_breadcrumbs separator: ' > '
    = yield

app/views/stores/index.html.haml
- title 'Shops'

%ul
  - @stores.each do |store|
    %li= link_to store.name, store_path(store)

app/views/stores/show.html.haml
- title @store.name

%table
  %tr
    %th id
    %th title
    %th author
    %th author_id
    %th quantity

  - @stocks.each do |stock|
    %tr
      %td= stock.id
      %td= stock.book.title
      %td= stock.book.author.name
      %td= stock.book.author.id
      %td= stock.quantity

ordered by book title.